language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'stable'
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
script:
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
